apiVersion: v1
kind: Service
metadata:
  name: {{ include "meos-web.fullname" . }}
  labels:
    {{- include "meos-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: phpfpm
      protocol: TCP
      name: phpfpm
  selector:
    {{- include "meos-web.selectorLabels" . | nindent 4 }}
